name: Test
on: pull_request
jobs:
  all_tests:
    name: All tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test